# Generated by Django 5.1 on 2026-04-15 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_category_image_url_alter_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Raw number of views in this category')),
                ('score', models.FloatField(default=0.0, help_text='Deep learning model prediction score (0-1)')),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='products.category')),
            ],
            options={
                'db_table': 'category_preferences',
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['session_id', '-score'], name='category_pr_session_5d0386_idx'), models.Index(fields=['user_id', '-score'], name='category_pr_user_id_a98d65_idx')],
                'unique_together': {('session_id', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Anonymous session identifier', max_length=100)),
                ('user_id', models.UUIDField(blank=True, db_index=True, help_text='Authenticated user ID (from user-service)', null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='products.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='products.product')),
            ],
            options={
                'db_table': 'product_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['session_id', 'viewed_at'], name='product_vie_session_aa5cf3_idx'), models.Index(fields=['user_id', 'viewed_at'], name='product_vie_user_id_caee54_idx'), models.Index(fields=['session_id', 'category'], name='product_vie_session_4d5b41_idx')],
            },
        ),
    ]
