# Generated by Django 5.1 on 2026-04-22 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='User UUID from user-service', max_length=36)),
                ('product_id', models.CharField(db_index=True, help_text='Product UUID from product-service', max_length=36)),
                ('action', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('search', 'Search'), ('add_to_cart', 'Add to Cart'), ('add_to_wishlist', 'Add to Wishlist'), ('purchase', 'Purchase'), ('review', 'Review'), ('share', 'Share')], db_index=True, help_text='Type of user behavior action', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When the action occurred')),
            ],
            options={
                'db_table': 'user_behaviors',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'action'], name='user_behavi_user_id_9de40f_idx'), models.Index(fields=['product_id', 'action'], name='user_behavi_product_182305_idx'), models.Index(fields=['user_id', 'timestamp'], name='user_behavi_user_id_cc4772_idx')],
            },
        ),
    ]
